name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Roda todo dia à meia-noite
  workflow_dispatch: # Permite que você rode manualmente AGORA
  push:
    branches:
    - main # Roda sempre que você fizer um push na main

permissions:
  contents: write # ESSA LINHA É A CHAVE DO SÊNIOR

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # Atualizado para v4

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Arthur-Vinicius
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Push to Output Branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
